node ("${BUILD_NODE}"){
   try{
      stage("Checkout"){
         dir("ossim-sandbox"){
            git branch: "${OSSIM_GIT_BRANCH}",
            url: "${GIT_PUBLIC_SERVER_URL}/ossim-sandbox.git",
            credentialsId: "${CREDENTIALS_ID}"
         }

      }
      stage("Create Build Image"){
         sh "${env.WORKSPACE}/ossim-sandbox/create-build-image.sh centos-7"
      }
      stage("Archive")
      {
         archiveArtifacts "*.tgz"
      }
   }
   finally
   {
      stage("Clean Workspace")
      {
         if ("${CLEAN_WORKSPACE}" == "true")
            step([$class: 'WsCleanup'])
      }
   }
}